# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shoji}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["CHIKURA Shinsaku"]
  s.date = %q{2009-12-10}
  s.description = %q{Shoji is a library for reading multiple format of table files.}
  s.email = %q{chsh@thinq.jp}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "javalib/poi-3.5-FINAL-20090928.jar",
     "javalib/poi-contrib-3.5-FINAL-20090928.jar",
     "javalib/poi-ooxml-3.5-FINAL-20090928.jar",
     "lib/shoji.rb",
     "lib/shoji/base.rb",
     "lib/shoji/csv.rb",
     "lib/shoji/excel.rb",
     "lib/shoji/excel/poi/cell_regulator.rb",
     "lib/shoji/excel/poi/reader.rb",
     "lib/shoji/excel/poi/workbook_stream.rb",
     "lib/shoji/java_loader.rb",
     "lib/shoji/text_base.rb",
     "lib/shoji/tsv.rb",
     "lib/shoji/utf8_file.rb",
     "lib/shoji_main.rb",
     "test/files/test01.csv",
     "test/files/test01.tsv",
     "test/files/test01.xls",
     "test/files/testcsv.data",
     "test/files/testtsv.data",
     "test/files/testxls.data",
     "test/helper.rb",
     "test/test_shoji.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Shoji is a library for reading multiple format of table files.}
  s.test_files = [
    "test/helper.rb",
     "test/test_shoji.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

